CREATE SEQUENCE SQ_ESTUDIANTES INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 CACHE 20;

CREATE TABLE "ESTUDIANTES" 
   ("ID_ESTUDIANTE" NUMBER(12,0) DEFAULT SQ_ESTUDIANTES.NEXTVAL NOT NULL ENABLE, 
	"ID_USUARIO" NUMBER(12,0) NOT NULL ENABLE, 
	CONSTRAINT "EST_PK" PRIMARY KEY ("ID_ESTUDIANTE"),
	CONSTRAINT "EST_USUARIO_FK" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "USUARIOS" ("ID_USUARIO") ENABLE);

CREATE INDEX ESTUDIANTES_ID_USUARIO ON ESTUDIANTES (ID_USUARIO);

COMMENT ON COLUMN "ESTUDIANTES"."ID_ESTUDIANTE" IS 'IDENTIFICADOR DEL ESTUDIANTE';
COMMENT ON COLUMN "ESTUDIANTES"."ID_USUARIO" IS 'IDENTIFICADOR DEL USUARIO';

INSERT INTO ESTUDIANTES (ID_USUARIO) VALUES (1); 