CREATE SEQUENCE SQ_TRAMOS_HORARIOS INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 CACHE 20;

CREATE TABLE "TRAMOS_HORARIOS" 
   ("ID_TRAMO_HORARIO" NUMBER(12,0) DEFAULT SQ_TRAMOS_HORARIOS.NEXTVAL NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(100) NOT NULL ENABLE, 
	CONSTRAINT "TRAHOR_PK" PRIMARY KEY ("ID_TRAMO_HORARIO"));

CREATE INDEX TRAMOS_HORARIOS_DESCRIPCION ON TRAMOS_HORARIOS (DESCRIPCION);

COMMENT ON COLUMN "TRAMOS_HORARIOS"."ID_TRAMO_HORARIO" IS 'IDENTIFICADOR DEL TRAMO HORARIO';
COMMENT ON COLUMN "TRAMOS_HORARIOS"."DESCRIPCION" IS 'DESCRIPCIÓN DEL TRAMO HORARIO';

INSERT INTO TRAMOS_HORARIOS (DESCRIPCION) VALUES ('9-12'); 
INSERT INTO TRAMOS_HORARIOS (DESCRIPCION) VALUES ('12-15'); 
INSERT INTO TRAMOS_HORARIOS (DESCRIPCION) VALUES ('15-18'); 
INSERT INTO TRAMOS_HORARIOS (DESCRIPCION) VALUES ('18-21'); 
INSERT INTO TRAMOS_HORARIOS (DESCRIPCION) VALUES ('21-24'); 
INSERT INTO TRAMOS_HORARIOS (DESCRIPCION) VALUES ('0-3'); 
INSERT INTO TRAMOS_HORARIOS (DESCRIPCION) VALUES ('3-6'); 
INSERT INTO TRAMOS_HORARIOS (DESCRIPCION) VALUES ('6-9'); 