CREATE SEQUENCE SQ_MATERIAS INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 CACHE 20;

CREATE TABLE "MATERIAS" 
   ("ID_MATERIA" NUMBER(12,0) DEFAULT SQ_MATERIAS.NEXTVAL NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(100) NOT NULL ENABLE, 
	"COLOR" VARCHAR2(6) NOT NULL ENABLE, 
	CONSTRAINT "MAT_PK" PRIMARY KEY ("ID_MATERIA"));

CREATE INDEX MATERIAS_ID_MATERIA ON MATERIAS (ID_MATERIA);
CREATE INDEX MATERIAS_NOMBRE ON MATERIAS (NOMBRE);
CREATE INDEX MATERIAS_COLOR ON MATERIAS (COLOR);

COMMENT ON COLUMN "MATERIAS"."ID_MATERIA" IS 'IDENTIFICADOR DE LA MATERIA';
COMMENT ON COLUMN "MATERIAS"."NOMBRE" IS 'NOMBRE DE LA MATERIA';
COMMENT ON COLUMN "MATERIAS"."COLOR" IS 'COLOR HEXADECIMAL DE LA MATERIA';

INSERT INTO MATERIAS (NOMBRE, COLOR) VALUES ('Español', 'FF775A'); 
INSERT INTO MATERIAS (NOMBRE, COLOR) VALUES ('Inglés', 'FFC545'); 
INSERT INTO MATERIAS (NOMBRE, COLOR) VALUES ('Francés', 'CAFE46'); 
INSERT INTO MATERIAS (NOMBRE, COLOR) VALUES ('Chino', '79FF63'); 
INSERT INTO MATERIAS (NOMBRE, COLOR) VALUES ('Alemán', '63FFD5'); 
INSERT INTO MATERIAS (NOMBRE, COLOR) VALUES ('Coreano', '69AAFF'); 
INSERT INTO MATERIAS (NOMBRE, COLOR) VALUES ('Japonés', '4E59FF'); 
INSERT INTO MATERIAS (NOMBRE, COLOR) VALUES ('Portugués', '0C75FF'); 
INSERT INTO MATERIAS (NOMBRE, COLOR) VALUES ('Italiano', '9F31FF'); 
INSERT INTO MATERIAS (NOMBRE, COLOR) VALUES ('Árabe', 'BE74FF'); 
INSERT INTO MATERIAS (NOMBRE, COLOR) VALUES ('Ruso', 'FF5EEB'); 