CREATE SEQUENCE SQ_CLASES INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 CACHE 20;

CREATE TABLE "CLASES" 
   ("ID_CLASE" NUMBER(12,0) DEFAULT SQ_PROFESORES.NEXTVAL NOT NULL ENABLE, 
	"ID_ESTUDIANTE" NUMBER(12,0) NOT NULL ENABLE,
	"ID_PROFESOR" NUMBER(12,0) NOT NULL ENABLE,
	"FECHA" DATE NOT NULL ENABLE, 
	"ID_TRAMO_HORARIO" NUMBER(12,0) NOT NULL ENABLE, 
	"ID_MATERIA" NUMBER(12,0) NOT NULL ENABLE, 
	CONSTRAINT "CLA_PK" PRIMARY KEY ("ID_CLASE"),
	CONSTRAINT "CLA_ESTUDIANTE_FK" FOREIGN KEY ("ID_ESTUDIANTE")
	  REFERENCES "ESTUDIANTES" ("ID_ESTUDIANTE") ENABLE,
	CONSTRAINT "CLA_PROFESOR_FK" FOREIGN KEY ("ID_PROFESOR")
	  REFERENCES "PROFESORES" ("ID_PROFESOR") ENABLE,
	CONSTRAINT "CLA_TRAMO_HORARIO_FK" FOREIGN KEY ("ID_TRAMO_HORARIO")
	  REFERENCES "TRAMOS_HORARIOS" ("ID_TRAMO_HORARIO") ENABLE,
	CONSTRAINT "CLA_MATERIA_FK" FOREIGN KEY ("ID_MATERIA")
	  REFERENCES "MATERIAS" ("ID_MATERIA") ENABLE);

CREATE INDEX CLASES_ID_ESTUDIANTE ON CLASES (ID_ESTUDIANTE);
CREATE INDEX CLASES_ID_PROFESOR ON CLASES (ID_PROFESOR);
CREATE INDEX CLASES_FECHA ON CLASES (FECHA);
CREATE INDEX CLASES_ID_TRAMO_HORARIO ON CLASES (ID_TRAMO_HORARIO);
CREATE INDEX CLASES_ID_MATERIA ON CLASES (ID_MATERIA);

COMMENT ON COLUMN "CLASES"."ID_CLASE" IS 'IDENTIFICADOR DE LA CLASE';
COMMENT ON COLUMN "CLASES"."ID_ESTUDIANTE" IS 'IDENTIFICADOR DEL ESTUDIANTE';
COMMENT ON COLUMN "CLASES"."ID_PROFESOR" IS 'IDENTIFICADOR DEL PROFESOR';
COMMENT ON COLUMN "CLASES"."FECHA" IS 'FECHA DE LA CLASE';
COMMENT ON COLUMN "CLASES"."ID_TRAMO_HORARIO" IS 'IDENTIFICADOR DEL TRAMO HORARIO';
COMMENT ON COLUMN "CLASES"."ID_MATERIA" IS 'IDENTIFICADOR DE LA MATERIA';

INSERT INTO CLASES (ID_ESTUDIANTE, ID_PROFESOR, FECHA, ID_TRAMO_HORARIO, ID_MATERIA) VALUES (1, 1, TO_DATE('20/05/2024', 'dd/mm/yyyy'), 1, 1); 