CREATE SEQUENCE SQ_USUARIOS INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 CACHE 20;

CREATE TABLE "USUARIOS" 
   (	"ID_USUARIO" NUMBER(12,0) DEFAULT SQ_USUARIOS.NEXTVAL NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(200) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(40) NOT NULL ENABLE, 
	"APELLIDOS" VARCHAR2(100) NOT NULL ENABLE, 
	"N_TELEFONO" NUMBER(9,0) NOT NULL ENABLE,
	CONSTRAINT "USU_PK" PRIMARY KEY ("ID_USUARIO"));

CREATE INDEX USUARIOS_EMAIL ON USUARIOS (EMAIL);
CREATE INDEX USUARIOS_NOMBRE ON USUARIOS (NOMBRE);
CREATE INDEX USUARIOS_APELLIDOS ON USUARIOS (APELLIDOS);
CREATE INDEX USUARIOS_TELEFONOS ON USUARIOS (TELEFONO);
CREATE INDEX USUARIOS_NOMBRE_APELLIDOS ON USUARIOS (NOMBRE, APELLIDOS);

COMMENT ON COLUMN "USUARIOS"."ID_USUARIO" IS 'IDENTIFICADOR DEL USUARIO';
COMMENT ON COLUMN "USUARIOS"."EMAIL" IS 'EMAIL DE USUARIO';
COMMENT ON COLUMN "USUARIOS"."NOMBRE" IS 'NOMBRE DEL USUARIO';
COMMENT ON COLUMN "USUARIOS"."APELLIDOS" IS 'APELLIDOS DEL USUARIO';
COMMENT ON COLUMN "USUARIOS"."N_TELEFONO" IS 'TELEFONO DEL USUARIO';

INSERT INTO USUARIOS (EMAIL, NOMBRE, APELLIDOS, TELEFONO) VALUES ('JOHNDOE@GMAIL.COM', 'JOHN', 'DOE', 123456789);  
INSERT INTO USUARIOS (EMAIL, NOMBRE, APELLIDOS, TELEFONO) VALUES ('JANADOE@GMAIL.COM', 'JANA', 'DOE', 987654321);  