services:
  - type: web
    name: learnmateback
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ./gradlew build
    startCommand: java -jar app.jar
    envVars:
      - key: PORT
        value: 8443